---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-common
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: ./flux/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
