---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: custom
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./flux/clusters/demo-cluster/custom
  prune: true
  dependsOn:
  - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
