apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  annotations:
    configmap.reloader.stakater.com/reload: "demo-app-config"
spec:
  selector:
    matchLabels:
      run: demo-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: demo-app
    spec:
      containers:
      - name: demo-app
        image: nikowoj900/demo-app:2023-10-01-1696146955 # {"$imagepolicy": "flux-system:demo-app"}
        env:
        - name: DEMO_DATA
          valueFrom:
            configMapKeyRef:
              name: demo-app-config
              key: demo
        ports:
        - containerPort: 80
