---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  image: nikowoj900/demo-app
  interval: 1m0s
  secretRef:
    name: regcred

