apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-app
  filterTags:
      pattern: "^[0-9]+(-[0-9]+)+-(?P<ts>[0-9]+)"
      extract: "$ts"
  policy:
    numerical:
      order: asc