name: Build and Deploy Demo app
on: 
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get current build date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Prep version
        id: prep-version
        shell: bash
        run: |
          timestamp=$(date +%s)
          currentdate=${{ steps.date.outputs.date }}
          echo "build_id=${currentdate}-${timestamp}" >> $GITHUB_OUTPUT
      - name: Build Demo app
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ steps.prep-version.outputs.build_id }}
        shell: bash
      - name: Push Demo app
        run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ steps.prep-version.outputs.build_id }}
        shell: bash